server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhuoye
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis:
  configuration:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:/mapper/*.xml
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-aliases-package: com.itheima.student.entity
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAI5tAd56ZWgggjdqLDHYAA
    accessKeySecret: 705AOC2aMN5kqsS5jDs0Mkuit4VcE0
    bucketName: arrk-tlias

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
